### ISSUE TITLE
Stackprinter failed, KeyError: 168

### ISSUE THREAD

**Issue by YashSinha1996** [cknd/stackprinter#9]
Stacktrace: 
```
Stackprinter failed:
  File "/datadrive/product_type_article/venv/lib/python3.7/site-packages/stackprinter/utils.py", line 52, in trim_source
    (snippet0, *meta0), *remaining_line = source_map[ln]
KeyError: 168
So here is the original traceback at least:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/datadrive/product_type_article/QA/using_gscraper.py", line 204, in <module>
    # main()
  File "/datadrive/product_type_article/QA/using_gscraper.py", line 168, in demo
    except Exception as e:
  File "/datadrive/product_type_article/QA/using_gscraper.py", line 165, in demo
    try:
  File "/datadrive/product_type_article/QA/using_gscraper.py", line 118, in get_possible_answers
    q_processed = get_restriction(ques, suppress=False)
  File "/datadrive/product_type_article/QA/QA_utils.py", line 134, in get_restriction
    raise e
  File "/datadrive/product_type_article/QA/QA_utils.py", line 123, in get_restriction
    rests = parse_question(q)
  File "/datadrive/product_type_article/QA/QA_utils.py", line 119, in <lambda>
    parse_question = lambda q: get_type_rel_pre(get_scored_class_kp(q.lower(), filter_kpe=False, questions=True, only_phrase_rel=True))
  File "/datadrive/product_type_article/QA/QA_utils.py", line 83, in get_type_rel_pre
    raise ValueError("Not a properly parsed Phrase.")
ValueError: Not a properly parsed Phrase.

```

**Comment by cknd** [comment]
🕵️ considering that one of the lines in traceback above is, in fact, a comment, it seems the code was edited post-import. not sure whether it should fail _more_ or _less_ gracefully in this scenario. 
closing for now, feel free to reopen if this doesn't make sense
